###
GET http://localhost:3000/api/v1/news/5f1df97a8351f44ce8349663
Content-Type: application/json
{
	
}
###
POST https://gamefactoring.azurewebsites.net/api/v1/news
Content-Type: application/json

{
	"hat":"Ano de 2018 ficará marcado pelo sucesso dos atletas nacionais no Circuito Mundial de Surfe",
	"title":"Com título de Medina e 11 na elite, 'Brazilian Storm' mostra que veio para ficar",
	"text":"A tempestade brasileira no surfe mostrou que não é passageira e representa a consolidação da modalidade no País. 'Brazilian Storm' é como os surfistas do Brasil são chamados no circuito. O ano de 2018 ficará marcado pelo sucesso dos atletas nacionais em diversas parte do mundo e tudo isso gera expectativa para 2019 e 2020, quando o surfe estreará no programa olímpico dos Jogos de Tóquio Gabriel Medina conquistou seu bicampeonato mundial no mesmo dia que Jesse Mendes ganhou a Tríplice Coroa Havaiana, uma honraria para os surfistas. Das 11 etapas realizadas no Circuito, os atletas brasileiros ganharam nove - nas últimas cinco temporadas três títulos do Mundial da elite ficaram nas mãos de surfistas brasileiros.",
	"author":"Da Redação, com Estadão Conteúdo",
	"img":"http://imagem.com.br/f_446243.jpg",
	"link":"https://esporte.uol.com.br/noticia/100000944120/com-bi-de-medina-e-11-na-elite-brazilian-storm-veio-para-ficar.html",
	"active":true
}
###
PUT http://localhost:3000/users/5e6e0b0ca1f5141b90d55cc9
Content-Type: application/json

{
  "name": "Claudia",
  "email": "claudia@marvel.com",
  "password": "123456",
  "gender": "Female"
}
###
DELETE 
POST https://gamefactoring.azurewebsites.net/api/v1/news/5f1e1f046df2b30011e26906
###
PATCH  http://localhost:3000/users/5e6e0b0ca1f5141b90d55cc9
Content-Type: application/json

{
  "name": "Jessica",
  "password": "123456",
}
###